version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx-proxy-reverse
    networks:
      - nginx-node-network
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app-node
    networks:
      - nginx-node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    networks:
      - nginx-node-network
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  nginx-node-network:
    driver: bridge